import type { ArtifactType } from '@/types/scenario'

// ============================================================================
// TUTOR MODE — Universal Concept Library
// ============================================================================
// One pre-written explainer per artifact type. These do NOT vary by stock or
// scenario — they teach the universal concept. The applied (specific) layer
// is generated by /api/tutor at request time.
// ============================================================================

export interface TutorConcept {
  artifact: ArtifactType
  title: string
  /** ~3 short paragraphs explaining the universal concept */
  paragraphs: string[]
  /** Glossary terms — render as dotted-underlined words in the body text */
  glossary: { term: string; def: string }[]
}

export const TUTOR_CONCEPTS: Record<ArtifactType, TutorConcept> = {
  // ───────────────────────────────────────────────────────────
  'price-chart': {
    artifact: 'price-chart',
    title: 'Reading the Price Chart',
    paragraphs: [
      'A candlestick chart shows what happened to a stock\'s price each day in a single glyph. The body shows where it opened and closed; a green/silver candle means it closed higher than it opened, a red candle means it closed lower. The thin wicks above and below show the highest and lowest prices reached during the day.',
      'Volume is the second half of the picture — the number of shares that changed hands. Big volume on a price move tells you institutional money is involved. Big price move with no volume usually means thin retail noise that won\'t hold.',
      'When you read a chart, look at three things in this order: trend (is the line generally going up, down, sideways?), recent change in trend (where did it turn?), and volume on the turning points (was the move conviction-backed?). Don\'t over-read individual candles in isolation — context is everything.',
    ],
    glossary: [
      { term: 'candlestick', def: 'A daily price glyph showing open, high, low, close prices in a single shape.' },
      { term: 'wick',        def: 'The thin lines above and below the candle body, marking the day\'s highs and lows.' },
      { term: 'volume',      def: 'Number of shares traded that day. High volume = high conviction.' },
      { term: 'trend',       def: 'The general direction of price over a window of time.' },
    ],
  },

  // ───────────────────────────────────────────────────────────
  'key-metrics': {
    artifact: 'key-metrics',
    title: 'Reading Key Metrics',
    paragraphs: [
      'Five numbers tell you most of what you need about a stock\'s valuation and risk profile. P/E ratio (price ÷ earnings per share) tells you how expensive the stock is relative to its profits — a high P/E means investors expect future growth, a low P/E means they don\'t. EPS is the company\'s profit divided by share count.',
      'Market cap is the total value of all the company\'s shares — it tells you how big the company is. Small caps are riskier and more volatile; large caps are more stable. The 52-week range (high and low over the past year) tells you where the stock is trading relative to its recent extremes.',
      'Beta is the most underused metric on this list. A beta of 1.0 means the stock moves in line with the broader market. Above 1.0 = more volatile (high-beta names crash and rally harder). Below 1.0 = defensive (less reactive to market swings). On a day like today, beta predicts how much you\'ll feel the chaos.',
    ],
    glossary: [
      { term: 'P/E ratio',  def: 'Price-to-earnings. How many rupees of stock price for each rupee of profit.' },
      { term: 'EPS',        def: 'Earnings per share. Net profit ÷ total shares outstanding.' },
      { term: 'market cap', def: 'Stock price × total shares outstanding. The company\'s total value.' },
      { term: 'beta',       def: 'How much the stock moves vs. the broader market. 1.0 = same; >1.0 = amplified; <1.0 = damped.' },
    ],
  },

  // ───────────────────────────────────────────────────────────
  'balance-sheet': {
    artifact: 'balance-sheet',
    title: 'Reading the Balance Sheet',
    paragraphs: [
      'A balance sheet is a snapshot of what a company owns (assets) and owes (liabilities) at a single point in time. The difference between the two is shareholder equity — the value left for owners after creditors are paid. The whole document fits on one page, which is why it\'s the fastest way to gauge financial health.',
      'Two ratios do most of the work. Debt-to-equity (D/E) tells you how much the company runs on borrowed money versus owner capital. Above 1.0 is risky for most sectors but normal for capital-intensive ones (airlines, banks, telecom). Current ratio (current assets ÷ current liabilities) tells you whether they can pay this year\'s bills. Below 1.0 is a yellow flag.',
      'Sector context is everything. A bank with D/E of 9 is normal — banks are leverage machines. An airline with D/E of 1.4 is normal — planes are expensive. The same number in different sectors tells very different stories. Always compare a company to its peers, not to an arbitrary "good" number.',
    ],
    glossary: [
      { term: 'assets',         def: 'Everything the company owns: cash, inventory, buildings, equipment.' },
      { term: 'liabilities',    def: 'Everything the company owes: loans, accounts payable, leases.' },
      { term: 'equity',         def: 'What\'s left for shareholders after liabilities are subtracted from assets.' },
      { term: 'D/E ratio',      def: 'Debt-to-equity. Total debt ÷ shareholder equity.' },
      { term: 'current ratio',  def: 'Short-term assets ÷ short-term liabilities. Below 1.0 = liquidity risk.' },
    ],
  },

  // ───────────────────────────────────────────────────────────
  'news-24h': {
    artifact: 'news-24h',
    title: 'Reading the News',
    paragraphs: [
      'Every news headline has a directional bias — bullish, bearish, or neutral — but the price reaction depends on whether the news was already expected. A "bad earnings miss" that everyone predicted may not move the stock; an unexpected miss can cause a 10% gap down. Markets price in expectations; news only matters when it surprises.',
      'When you read a 24-hour news feed, ask three questions: (1) Is this priced in already? (2) Does it affect this specific company or the whole sector? (3) What\'s the second-order effect? An oil price crash hurts oil refiners directly but helps airlines (lower fuel costs) and consumers (lower petrol). The second-order effects are where alpha lives.',
      'Beware the "cluster" pattern. When 3+ negative headlines for the same sector hit within 24 hours, the move is often bigger than any single headline would predict — institutional traders pile out together. The Covid Day Zero pre-market is a textbook example.',
    ],
    glossary: [
      { term: 'priced in',           def: 'Market expectation already reflected in the current stock price.' },
      { term: 'second-order effect', def: 'A consequence of a consequence. Oil down → airlines benefit (lower fuel).' },
      { term: 'cluster pattern',     def: 'Multiple related headlines hitting in a short window — usually amplifies moves.' },
    ],
  },

  // ───────────────────────────────────────────────────────────
  'holdings': {
    artifact: 'holdings',
    title: 'Reading Institutional Holdings',
    paragraphs: [
      'Look at who owns the stock — and you learn a lot about how it will behave. Promoters (founding families and parent companies) typically hold long-term, providing price stability. Domestic institutions (LIC, mutual funds) move more slowly. Foreign institutions (BlackRock, Vanguard, sovereign wealth funds) react fastest to global risk-off events — they\'re often the first to sell in a panic.',
      'Two patterns matter most. High promoter holding (>40%) means insider conviction is strong, but float (publicly tradable shares) is thin — moves can be exaggerated. High foreign institutional holding (>20%) means the stock is exposed to "risk-off" capital flight when global VIX spikes; rupee weakness amplifies the effect.',
      'Sometimes you\'ll see "smart money" repositioning before the broader market reacts. If a sovereign wealth fund quietly trimmed its stake last quarter and the price has held up, that\'s a signal worth investigating. Pre-pandemic, foreign institutions had been net sellers of Indian equities for two consecutive months — a leading indicator that retail traders missed.',
    ],
    glossary: [
      { term: 'promoter',     def: 'Founding family / parent company. Long-term holders, vote control.' },
      { term: 'float',        def: 'Shares actually available for public trading (not held by promoters).' },
      { term: 'risk-off',     def: 'Global mood where investors flee risky assets for safer ones.' },
      { term: 'smart money',  def: 'Institutional / sophisticated investors whose moves often precede broader trends.' },
    ],
  },

  // ───────────────────────────────────────────────────────────
  'sector-position': {
    artifact: 'sector-position',
    title: 'Reading Sector Position',
    paragraphs: [
      'No stock moves in isolation. Each one sits inside a sector that responds to specific macro factors — oil prices, interest rates, currency, consumer sentiment, regulation. Understanding which factors a stock is most sensitive to is the foundation of trading the news.',
      'Correlations tell you the relationship\'s strength. A correlation of +0.7 between RELIANCE and crude oil means when oil moves up 10%, RELIANCE typically moves up 7%. A correlation of −0.6 between INDIGO and oil means oil up 10% = INDIGO down 6%. These aren\'t laws — they\'re tendencies. They break in extreme conditions, which is when the biggest gains and losses happen.',
      'Sensitivity to factors is sometimes asymmetric — stocks can be more sensitive to bad news than good news. A pharma stock might rally 3% on a positive trial result but fall 12% on FDA action against a key plant. Always weigh sensitivities directionally: what hurts more, what helps less?',
    ],
    glossary: [
      { term: 'correlation', def: 'Statistical measure of how two things move together. +1 = perfect lockstep, -1 = perfect opposite.' },
      { term: 'macro factor', def: 'Broad economic variable (oil, rates, currency) that affects many stocks at once.' },
      { term: 'asymmetric sensitivity', def: 'A stock that reacts more to bad news than good news (or vice versa).' },
    ],
  },
}
