import type { MiniGame } from '../game-types'

export const PLAN_BUILDER: MiniGame = {
  slug: 'trading-plan',
  title: 'Plan Builder',
  tagline: 'Pick the rules that make a complete trading plan — across 6 setups.',
  accentColor: '06B6D4',
  passThreshold: 0.66,
  customMode: 'plan-dragdrop',
  rounds: [
    {
      id: 'pb1', kind: 'select_rules',
      context: 'Setup · 1 of 6 · Trend-Following Plan',
      prompt: 'You are building a trend-following plan for swing trading. Which rules belong?',
      minCorrect: 4,
      rules: [
        { text: 'Enter only when price > MA20 > MA50 (stack confirmed)', correct: true },
        { text: 'Stop loss = 1.5 × ATR below entry, hard rule', correct: true },
        { text: 'Position size = 1% of account ÷ stop distance', correct: true },
        { text: 'Exit when MA20 crosses below MA50 (death cross)', correct: true },
        { text: 'Add to position whenever you "feel bullish"', correct: false },
        { text: 'Move stop loss DOWN if trade goes against you', correct: false },
        { text: 'Risk 5% of account on every trade', correct: false },
        { text: 'Hold positions through earnings without size reduction', correct: false },
      ],
      explanation: 'A trend-following plan needs: (1) clear entry signal, (2) hard stop loss, (3) calculated position size, (4) defined exit. The wrong rules either lack discipline or violate the core principle of cutting losses.',
    },
    {
      id: 'pb2', kind: 'select_rules',
      context: 'Setup · 2 of 6 · Risk Rules',
      prompt: 'You are writing the risk-management section of your plan. Which rules are non-negotiable?',
      minCorrect: 4,
      rules: [
        { text: 'Maximum 2% risk per trade, ever', correct: true },
        { text: 'Maximum 6% portfolio heat across all open trades', correct: true },
        { text: 'Stop trading for the day after 2 consecutive losses', correct: true },
        { text: 'Never trade larger after a loss to "make it back"', correct: true },
        { text: 'Risk is whatever feels right that day', correct: false },
        { text: 'Skip stop loss if you have high conviction', correct: false },
        { text: 'Increase size after a win streak', correct: false },
        { text: 'No daily loss limit — pros never quit', correct: false },
      ],
      explanation: 'Risk rules are written to protect you from yourself. The "wrong" rules feel intuitive in the moment but are how careers end. Pre-commit to the right rules when calm — execute when not.',
    },
    {
      id: 'pb3', kind: 'select_rules',
      context: 'Setup · 3 of 6 · Trade Journal Fields',
      prompt: 'Which fields belong in every journal entry for every trade?',
      minCorrect: 4,
      rules: [
        { text: 'Entry price, time, and rationale (your thesis)', correct: true },
        { text: 'Stop loss level and why you chose it', correct: true },
        { text: 'Position size and % of account at risk', correct: true },
        { text: 'Exit reason: target hit, stop hit, plan changed', correct: true },
        { text: 'Whether you "felt confident" about the trade', correct: false },
        { text: 'A 1-paragraph summary of how the market made you feel', correct: false },
        { text: 'Predictions for next week\'s market', correct: false },
        { text: 'How much profit you "could have" made if held longer', correct: false },
      ],
      explanation: 'A journal is data, not therapy. Capture facts: thesis, risk, outcome. Avoid emotional retrospectives — they teach you nothing actionable. The "could have" field is the worst — it teaches regret instead of process.',
    },
    {
      id: 'pb4', kind: 'select_rules',
      context: 'Setup · 4 of 6 · Pre-Trade Checklist',
      prompt: 'Before clicking "Buy," which questions must always be answered?',
      minCorrect: 4,
      rules: [
        { text: 'Is the broad market regime favorable to my direction?', correct: true },
        { text: 'Where exactly is my stop loss? (specific number)', correct: true },
        { text: 'What is my position size based on stop distance?', correct: true },
        { text: 'Why am I taking THIS trade? (one-sentence thesis)', correct: true },
        { text: 'Has the price moved 3%+ today already?', correct: false },
        { text: 'Did my friend recommend this stock?', correct: false },
        { text: 'How do I feel about it?', correct: false },
        { text: 'Will this trade make me feel smart?', correct: false },
      ],
      explanation: 'The 4-question checklist (regime, stop, size, thesis) takes 30 seconds and prevents 80% of bad trades. Force yourself to write the answers down before pressing the button.',
    },
    {
      id: 'pb5', kind: 'select_rules',
      context: 'Setup · 5 of 6 · Exit Rules',
      prompt: 'For a swing trade, which exit conditions are valid in your plan?',
      minCorrect: 4,
      rules: [
        { text: 'Stop loss hit', correct: true },
        { text: 'Target price hit (pre-defined)', correct: true },
        { text: 'Thesis invalidated by news or chart structure', correct: true },
        { text: 'Trail stop activated and triggered', correct: true },
        { text: 'You feel like the trade has "had its run"', correct: false },
        { text: 'Random tweet from an influencer changes your view', correct: false },
        { text: '"It\'s been long enough" — exit by feel', correct: false },
        { text: 'Price went against you 1% — emotional exit', correct: false },
      ],
      explanation: 'Valid exits are RULE-DRIVEN: stop, target, invalidation, trail. Anything else is emotional and reduces edge. If you find yourself wanting to exit "by feel," that is a signal you have no plan.',
    },
    {
      id: 'pb6', kind: 'select_rules',
      context: 'Setup · 6 of 6 · Performance Review',
      prompt: 'In your weekly review, which questions create real edge improvement?',
      minCorrect: 4,
      rules: [
        { text: 'Did I follow my plan on every trade? (yes/no per trade)', correct: true },
        { text: 'Were my stops respected without being moved?', correct: true },
        { text: 'What was my expectancy this week (avg win × win rate − avg loss × loss rate)?', correct: true },
        { text: 'Did I size correctly relative to my edge?', correct: true },
        { text: 'How many trades did I "feel" good about?', correct: false },
        { text: 'Did the market reward my opinions?', correct: false },
        { text: 'Which influencer was right this week?', correct: false },
        { text: 'How much "could have" been earned?', correct: false },
      ],
      explanation: 'The right questions measure PROCESS, not outcome. You can have a profitable week with bad process and a losing week with great process. Long-term success comes from grading process, not luck.',
    },
  ],
}
