import type { MiniGame } from '../game-types'

export const POSITION_SIZER: MiniGame = {
  slug: 'risk-management',
  title: 'Position Sizer',
  tagline: 'Compute the correct share count for 6 risk scenarios.',
  accentColor: 'FF1F1F',
  passThreshold: 0.66,
  rounds: [
    {
      id: 'ps1', kind: 'calc',
      context: 'Calc · 1 of 6',
      prompt: 'Account: ₹1,00,000. Risk per trade: 2% of account = ₹2,000. Entry: ₹500. Stop loss: ₹490 (₹10 below entry). How many shares should you buy?',
      hint: 'Formula: (max loss in ₹) ÷ (entry price − stop price)',
      unit: 'shares',
      acceptable: { min: 195, max: 205, ideal: 200 },
      explanation: '₹2,000 max loss ÷ ₹10 risk per share = 200 shares. Notice: position size is determined by your STOP LOSS distance, not by how confident you feel.',
    },
    {
      id: 'ps2', kind: 'calc',
      context: 'Calc · 2 of 6',
      prompt: 'Account: ₹2,50,000. Risk: 1% per trade = ₹2,500. Entry: ₹800. Stop: ₹750. How many shares?',
      hint: 'Risk per share is ₹50 here.',
      unit: 'shares',
      acceptable: { min: 48, max: 52, ideal: 50 },
      explanation: '₹2,500 ÷ ₹50 = 50 shares. Wider stops mean smaller size for the same risk. This is why "tight stops" let you size bigger.',
    },
    {
      id: 'ps3', kind: 'calc',
      context: 'Calc · 3 of 6',
      prompt: 'You buy 100 shares of HDFC at ₹1,500 with a stop at ₹1,455. What is your maximum rupee loss if stopped out?',
      hint: 'Loss per share × number of shares.',
      unit: '₹',
      acceptable: { min: 4400, max: 4600, ideal: 4500 },
      explanation: '₹45 × 100 = ₹4,500. If this is more than 2% of your account, your position is too big or your stop is too wide.',
    },
    {
      id: 'ps4', kind: 'calc',
      context: 'Calc · 4 of 6',
      prompt: 'Account: ₹50,000. Entry: ₹200. Target: ₹230. Stop: ₹190. What is your reward-to-risk (R:R) ratio?',
      hint: '(Target − Entry) ÷ (Entry − Stop)',
      unit: ':1',
      acceptable: { min: 2.9, max: 3.1, ideal: 3 },
      explanation: 'Reward = ₹30, Risk = ₹10 → R:R = 3:1. Pros generally want at least 2:1 to compensate for losing trades. 3:1 is healthy.',
    },
    {
      id: 'ps5', kind: 'calc',
      context: 'Calc · 5 of 6',
      prompt: 'You have ₹3,00,000. You want to risk ONLY ₹3,000 on this trade. Entry: ₹400. Stop: ₹385. Maximum shares you can buy?',
      hint: 'Risk per share is ₹15.',
      unit: 'shares',
      acceptable: { min: 195, max: 205, ideal: 200 },
      explanation: '₹3,000 ÷ ₹15 = 200 shares. Notional position is ₹80,000 (~27% of wallet) — but the RISK is only 1% of the account. That distinction is everything.',
    },
    {
      id: 'ps6', kind: 'calc',
      context: 'Calc · 6 of 6',
      prompt: 'You took a ₹500 loss on Trade A and a ₹300 loss on Trade B. To "make it back," you decide to risk ₹2,000 on Trade C. What % of a ₹1,00,000 account is now at risk on a single trade?',
      hint: 'Just the risk on Trade C as % of account.',
      unit: '%',
      acceptable: { min: 1.9, max: 2.1, ideal: 2 },
      explanation: '2% — but this is revenge sizing. Doubling your risk after losses is how accounts blow up. Stick to your fixed % regardless of recent P&L.',
    },
  ],
}
